"""fix nextcloud_account fk cascade drift

Revision ID: d6a1af80d5bf
Revises: 
Create Date: 2026-09-10 20:47:41.803292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a1af80d5bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('nextcloud_account_user_id_fkey'), 'nextcloud_account', type_='foreignkey')
    op.create_foreign_key(None, 'nextcloud_account', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nextcloud_account', type_='foreignkey')
    op.create_foreign_key(op.f('nextcloud_account_user_id_fkey'), 'nextcloud_account', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
